### PR TITLE
Colors andadjectives

### PR DESCRIPTION
**Pull request by Mingxi-Shi**

### CODE REVIEW

**Comment by jim-parry** [comment]
Oh no - your other PR created more conflicts here!

**Comment by jim-parry** [comment]
oh no - now we have a different conflict

**Comment by Mingxi-Shi** [comment]
I don't know exactly what I need to do,
But can I resolve conflicts directly on github's website?
(On this page there is a button named of Resolve conflicts)

**Comment by jim-parry** [comment]
I am not sure. You might be able to, since it is your PR. Try it and we'll see!

**Comment by Mingxi-Shi** [comment]
Please check it again.
I resolved the conflicts, if it is okay, I will do the same operation on my other PR.

**Pull request merged**
